export { default as ErrorBoundary } from './ErrorBoundary'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as LegalPage } from './LegalPage'
export { default as ScrollToTop } from './ScrollToTop'
export { default as SeoManager } from './SeoManager'
export { default as SkipToContent } from './SkipToContent'
export { default as WhatsAppFloat } from './WhatsAppFloat'
